inherit_from:
  - .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
  TargetRubyVersion: 3.1

Style/StringLiterals:
  EnforcedStyle: single_quotes

require:
  - rubocop-rails

AllCops:
  Exclude:
    - 'Gemfile'
    - 'app/admin/**/*'
    - 'app/controllers/**/*'
    - 'app/helpers/**/*'
    - 'app/models/**/*'
    - 'config/**/*'
    - 'db/migrate/**/*'
    - 'db/seeds.rb'
    - 'bin/**/*'


